CREATE TABLE IF NOT EXISTS STATE (STATE_ID LONG PRIMARY KEY, STATE_NAME VARCHAR(20));

CREATE TABLE IF NOT EXISTS CRIME_YEAR (YEAR_ID LONG PRIMARY KEY, YEAR_NAME VARCHAR(4));

CREATE TABLE IF NOT EXISTS CRIME (CRIME_ID LONG PRIMARY KEY, CRIME_NAME VARCHAR(10));

CREATE TABLE IF NOT EXISTS CRIME_REPORT (
    REPORT_ID LONG PRIMARY KEY,
    STATE_ID LONG,
    YEAR_ID LONG,
    CRIME_ID LONG,
    COUNT LONG,
    FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID),
    FOREIGN KEY (YEAR_ID) REFERENCES CRIME_YEAR(YEAR_ID),
    FOREIGN KEY (CRIME_ID) REFERENCES CRIME(CRIME_ID)
);
